#:import AppSpacing kartupedia.core.theme.AppSpacing
#:import AppRadius kartupedia.core.theme.AppRadius
#:import AppTypography kartupedia.core.theme.AppTypography


<AppButton>:
    orientation: "horizontal"
    padding: AppSpacing.MD, AppSpacing.SM
    size_hint_y: None
    height: dp(48)
    canvas.before:
        Color:
            rgba: root.bg_color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [AppRadius.MD]

    Label:
        text: root.text
        color: root.text_color
        font_size: AppTypography.BODY
        bold: True
        halign: "center"
        valign: "middle"
        text_size: self.size
